# Generated by Django 3.1.6 on 2021-02-14 14:50

from django.db import migrations, models
import django.db.models.deletion
import modliszka.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, validators=[modliszka.validators.check_length])),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('description', models.CharField(default='', max_length=256, verbose_name='Opis')),
                ('price', models.FloatField(validators=[modliszka.validators.check_price], verbose_name='Cena')),
                ('typ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modliszka.producttyp')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('size', models.IntegerField(choices=[(1, 'small'), (2, 'normal'), (3, 'large')])),
                ('price', models.FloatField()),
                ('toppings', models.ManyToManyField(to='modliszka.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modliszka.client')),
                ('products', models.ManyToManyField(to='modliszka.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modliszka.card')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modliszka.product')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modliszka.client'),
        ),
        migrations.AddField(
            model_name='card',
            name='products',
            field=models.ManyToManyField(through='modliszka.CarProduct', to='modliszka.Product'),
        ),
    ]
