# Generated by Django 3.1.6 on 2021-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modliszka', '0002_auto_20210213_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
