# Generated by Django 3.1.6 on 2021-02-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modliszka', '0003_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='products',
        ),
        migrations.CreateModel(
            name='CarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modliszka.card')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modliszka.product')),
            ],
        ),
    ]
