# Generated by Django 3.1.6 on 2021-02-14 09:16

from django.db import migrations, models
import modliszka.models


class Migration(migrations.Migration):

    dependencies = [
        ('modliszka', '0005_card_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[modliszka.models.check_price], verbose_name='Cena'),
        ),
    ]
