# Generated by Django 3.1.6 on 2021-02-14 10:36

from django.db import migrations, models
import modliszka.validators


class Migration(migrations.Migration):

    dependencies = [
        ('modliszka', '0006_auto_20210214_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=128, validators=[modliszka.validators.check_length]),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('size', models.IntegerField(choices=[(1, 'small'), (2, 'normal'), (3, 'large')])),
                ('price', models.FloatField()),
                ('toppings', models.ManyToManyField(to='modliszka.Topping')),
            ],
        ),
    ]
